FROM debian:buster

RUN apt-get update && apt-get upgrade -y
RUN apt-get -y install wget
RUN apt install nginx -y

COPY nginx.conf /etc/nginx/sites-available/default
COPY start.sh .

CMD ["sh", "start.sh"]

#docker run -p 443:443 4c9